# Generated by Django 3.1.14 on 2022-01-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='na', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='na', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='subtitle',
            field=models.CharField(default='na', max_length=250),
            preserve_default=False,
        ),
    ]
